
Instructions for benchmark on Summitdev:

.  Edit run-swift-sdev.sh to
.. set PROJECT
.. set Swift/T location (if needed)
. Run:
----
$ export PROCS=16 PPN=16
$ ./run-swift-sdev.sh loop.swift -n=$((PROCS*2))
----

This will run loop.swift

Try to run as many PROCS as possible, by powers of 2: 16,32,...
Ideally get to 4K or so.

Then share the output directories with me.

== Singularity

----
singularity shell /lustre/atlas/world-shared/stf007/ForArvind/arvind4_ppc64.img
----

Works on the login node.

Use python3 for keras, but this must be done on a compute node.

== Next steps

=== Done

. Basic shell task from Swift/T at 4K cores

=== TODO

. Load Keras from Python in container in shell script (no Swift/T)
. Run a CANDLE Benchmark from Python in container in shell script (no Swift/T)
. Run dummy task.sh in the container from Swift/T
. Run Python in container from Swift/T
. Run Python+Keras in container from Swift/T
. Run Python+Keras+Benchmark (one shot) in container from Swift/T
. Run mlrMBO workflow in container
