
= Notes for Scaling Study on Summitdev/Summit

== Quick start

.  Edit run-swift-sdev.sh to
.. set PROJECT
.. set Swift/T location (if needed)
. Run:

----
$ export PROCS=16 PPN=16
$ ./run-swift-sdev.sh loop.swift -n=$((PROCS*10)) --task=task-exit.sh
----

This will run loop.swift and invoke task-exit.sh 160 times.

We can easily copy task-exit.sh to run our other experiments.


== Methodology

. Try to run as many PROCS as possible, by powers of 2: 4,8,16,...,2K
. Record ADLB Elapsed time using the scan.sh script
. Post the results in the spreadsheet here:
https://docs.google.com/spreadsheets/d/1NYxOFd-iedl03ilxX1mYzE5hcTnvs3fMAmcHxGqQK_k

== Conventions

. Save all your TURBINE_OUTPUT directories, use the default naming scheme
. Make them public when you get the chance

== Singularity

----
singularity shell /lustre/atlas/world-shared/stf007/ForArvind/arvind4_ppc64.img
----

Works on the login node.

Use python3 for keras, but this must be done on a compute node.

Request features with Hong-Jun Yoon <yoonh@ornl.gov>

== Experiments

Wozniak/Jain will test up to 32*16=512 processes on Summitdev, Maheshwari will run the bigger jobs on Summit

[width="50%"]
|====
| Sheet   | User      | Task         | Description
| n:bash  | Wozniak   | task-exit.sh | Native call to bash
| c:bash  | Jain      | ???          | Container call to bash
| n:keras | Maheswari | ???          | Native call to keras
| c:keras | Jain      | ???          | Container call to keras
|====

=== Done

. Basic shell task from Swift/T - need to re-run with more tasks (sheet: n:bash) (Wozniak)

=== TODO

. Load Keras from Python in container in shell script (no Swift/T) (Jain - Works)
. Run a CANDLE Benchmark from Python in container in shell script (no Swift/T) (Jain - Works)
. Run dummy task.sh in the container from Swift/T (Jain - Works)
. Run Python in container from Swift/T (Jain?)
. Run Python+Keras in container from Swift/T (Jain?)
. Run Python+Keras+Benchmark (one shot) in container from Swift/T (Jain?)
. Run mlrMBO workflow in container (Jain- needs dependencies)
.. Need R
