
= Cell-GREP

== Overview

The GDSC dataset (and possibly others) contains cell lines that have metadata in https://www.cellosaurus.org[Cellosaurus].  To create data subsets based on demographic information, we need to be able to select from GDSC based on metadata.  Cell-GREP makes it easy to create a new dataset consisting of data selected from GDSC via metadata string matching.

== Usage

=== Step 1: Download the data

==== Get the Cellosaurus XML

----
$ wget https://ftp.expasy.org/databases/cellosaurus/cellosaurus.xml
----

==== Get the GDSC XLSX

----
$ wget https://ftp.mcs.anl.gov/pub/candle/public/improve/reproducability/DeepTTC/GDSC2_fitted_dose_response_25Feb20.xlsx
----

Then convert the XLSX to CSV via Excel "Save As".  By convention we call this `$GDSC`.

=== Step 2: Make the table

First, we extract the Cellosaurus data to a fast table:

----
$ python extract.py cellosaurus.xml table.txt
----

See also `python extract.py --help`

=== Step 3: Run the query

For example, to extract all males in GDSC, do:

----
$ python cell_grep.py $GDSC table.txt "Male" select-Male.txt
----

To extract all females in GDSC, do:
----
$ python cell_grep.py $GDSC table.txt "Female" select-Female.txt
# or
$ python cell_grep.py $GDSC table.txt --negate "Male" select-not-Male.txt
----

The pattern in quotes is any text substring against the metadata in `table.txt`.

See also `python cell_grep.py --help`
